### ISSUE TITLE
Don't alert about logs that you wrote

### ISSUE THREAD

**Issue by nbebout** [lfkeitel/Cheesto-Chrome#1]
It would be nice if Cheesto-Chrome didn't alert you to logs that you made, and only alerted to logs that other people made.

**Comment by lfkeitel** [comment]
Right now this would be difficult/inconvenient to implement. Currently there is no ability to filter logs by author. One way to do this would be to ask the user to enter a username in the options page and compare the most recent logs with that username ignoring any log with the same user.

In version 6.1 of Dandelion the /api/users/getuser endpoint will no longer require a user id and will return the user data with just an api key. With this and added support for searching on a log's author this can be done. In short, this won't happen until 6.1 comes out in late Dec.
